/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as RecettesRouteImport } from './routes/recettes'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as GroupeRouteImport } from './routes/groupe'
import { Route as FrigoRouteImport } from './routes/frigo'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CommunauteRouteImport } from './routes/communaute'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecetteIdRouteImport } from './routes/recette.$id'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const RecettesRoute = RecettesRouteImport.update({
  id: '/recettes',
  path: '/recettes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupeRoute = GroupeRouteImport.update({
  id: '/groupe',
  path: '/groupe',
  getParentRoute: () => rootRouteImport,
} as any)
const FrigoRoute = FrigoRouteImport.update({
  id: '/frigo',
  path: '/frigo',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunauteRoute = CommunauteRouteImport.update({
  id: '/communaute',
  path: '/communaute',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecetteIdRoute = RecetteIdRouteImport.update({
  id: '/recette/$id',
  path: '/recette/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/communaute': typeof CommunauteRoute
  '/courses': typeof CoursesRoute
  '/frigo': typeof FrigoRoute
  '/groupe': typeof GroupeRoute
  '/historique': typeof HistoriqueRoute
  '/onboarding': typeof OnboardingRoute
  '/parametres': typeof ParametresRoute
  '/planning': typeof PlanningRoute
  '/recettes': typeof RecettesRoute
  '/stats': typeof StatsRoute
  '/recette/$id': typeof RecetteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/communaute': typeof CommunauteRoute
  '/courses': typeof CoursesRoute
  '/frigo': typeof FrigoRoute
  '/groupe': typeof GroupeRoute
  '/historique': typeof HistoriqueRoute
  '/onboarding': typeof OnboardingRoute
  '/parametres': typeof ParametresRoute
  '/planning': typeof PlanningRoute
  '/recettes': typeof RecettesRoute
  '/stats': typeof StatsRoute
  '/recette/$id': typeof RecetteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/communaute': typeof CommunauteRoute
  '/courses': typeof CoursesRoute
  '/frigo': typeof FrigoRoute
  '/groupe': typeof GroupeRoute
  '/historique': typeof HistoriqueRoute
  '/onboarding': typeof OnboardingRoute
  '/parametres': typeof ParametresRoute
  '/planning': typeof PlanningRoute
  '/recettes': typeof RecettesRoute
  '/stats': typeof StatsRoute
  '/recette/$id': typeof RecetteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/communaute'
    | '/courses'
    | '/frigo'
    | '/groupe'
    | '/historique'
    | '/onboarding'
    | '/parametres'
    | '/planning'
    | '/recettes'
    | '/stats'
    | '/recette/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/communaute'
    | '/courses'
    | '/frigo'
    | '/groupe'
    | '/historique'
    | '/onboarding'
    | '/parametres'
    | '/planning'
    | '/recettes'
    | '/stats'
    | '/recette/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/communaute'
    | '/courses'
    | '/frigo'
    | '/groupe'
    | '/historique'
    | '/onboarding'
    | '/parametres'
    | '/planning'
    | '/recettes'
    | '/stats'
    | '/recette/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CommunauteRoute: typeof CommunauteRoute
  CoursesRoute: typeof CoursesRoute
  FrigoRoute: typeof FrigoRoute
  GroupeRoute: typeof GroupeRoute
  HistoriqueRoute: typeof HistoriqueRoute
  OnboardingRoute: typeof OnboardingRoute
  ParametresRoute: typeof ParametresRoute
  PlanningRoute: typeof PlanningRoute
  RecettesRoute: typeof RecettesRoute
  StatsRoute: typeof StatsRoute
  RecetteIdRoute: typeof RecetteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recettes': {
      id: '/recettes'
      path: '/recettes'
      fullPath: '/recettes'
      preLoaderRoute: typeof RecettesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groupe': {
      id: '/groupe'
      path: '/groupe'
      fullPath: '/groupe'
      preLoaderRoute: typeof GroupeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frigo': {
      id: '/frigo'
      path: '/frigo'
      fullPath: '/frigo'
      preLoaderRoute: typeof FrigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communaute': {
      id: '/communaute'
      path: '/communaute'
      fullPath: '/communaute'
      preLoaderRoute: typeof CommunauteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recette/$id': {
      id: '/recette/$id'
      path: '/recette/$id'
      fullPath: '/recette/$id'
      preLoaderRoute: typeof RecetteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CommunauteRoute: CommunauteRoute,
  CoursesRoute: CoursesRoute,
  FrigoRoute: FrigoRoute,
  GroupeRoute: GroupeRoute,
  HistoriqueRoute: HistoriqueRoute,
  OnboardingRoute: OnboardingRoute,
  ParametresRoute: ParametresRoute,
  PlanningRoute: PlanningRoute,
  RecettesRoute: RecettesRoute,
  StatsRoute: StatsRoute,
  RecetteIdRoute: RecetteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
